const bigmovie = document.getElementById("bigmovie");
const bigImage = document.getElementById("bigImage");
const bigTitle = document.getElementById("bigTitle");
const bigDescription = document.getElementById("bigDescription");

const descriptions = {
  "Back to the Future": "Robert Zemeckis’ Back to the Future is a rollicking sci-fi comedy where teenager Marty McFly (Michael J. Fox) zaps from 1985 to 1955 in a DeLorean time machine built by eccentric scientist Doc Brown (Christopher Lloyd). Marty must ensure his teenage parents fall in love to avoid erasing himself from existence, all while dodging bullies and rock ‘n’ rolling his way back to the future. The film’s time travel hinges on a single timeline where changing the past directly alters the future—think fading Polaroids and shifting family dynamics. It’s a “causal loop” model: Marty’s actions in 1955 shape his 1985 reality. What’s right? The idea that small changes can ripple forward aligns with chaos theory’s butterfly effect. What’s wrong? The instant fading of Marty’s siblings is dramatic but unrealistic—time paradoxes would likely be messier or unresolvable. The film prioritizes fun over physics, ignoring real-world constraints like energy requirements for time travel.",
  "Avengers: Endgame": "The Russo Brothers’ Avengers: Endgame is a superhero epic where the Avengers, reeling from Thanos’ universe-altering snap, use time travel to undo his devastation. Led by Tony Stark (Robert Downey Jr.), they navigate the “Quantum Realm” to revisit past MCU moments, collecting Infinity Stones to rewrite history. The film’s time travel rejects changing the past directly; instead, it uses a multiverse model—altering the past creates new branching timelines, leaving the original intact. What’s right? This aligns with quantum mechanics’ “many-worlds” interpretation, where every choice spawns a parallel universe. It cleverly avoids paradoxes like the grandfather paradox. What’s wrong? The Quantum Realm is a plot-convenient gimmick, not grounded in real physics, and the rules for timeline branching get murky (e.g., how certain characters return). The emotional stakes shine, but the science is more comic-book than Einstein.",
  "Interstellar": "Christopher Nolan’s Interstellar is a cerebral sci-fi odyssey where astronaut Cooper (Matthew McConaughey) ventures through a wormhole to find a new home for humanity. Time travel emerges via a black hole’s gravitational time dilation—near the singularity, hours for Cooper equal years on Earth. A mysterious “tesseract” later allows Cooper to influence the past subtly. The film suggests a closed-loop timeline: the future influences the past, but the past doesn’t change the future. What’s right? Time dilation is spot-on, rooted in Einstein’s relativity—time slows near massive objects. The wormhole concept is plausible, inspired by physicist Kip Thorne. What’s wrong? The tesseract’s mechanics lean into speculative metaphysics, not science, and the “humans from the future” bootstrap paradox feels circular. It’s a poetic blend of hard science and hopeful fiction.",
  "Passengers":"Morten Tyldum’s Passengers is a sleek sci-fi romance where Jim (Chris Pratt) and Aurora (Jennifer Lawrence) awaken early on a century-long space voyage. Time travel isn’t explicit, but the film toys with temporal displacement—hibernation pods freeze time for passengers, creating a “future” where they’re out of sync with their destination’s timeline. Changing the past or future isn’t a focus; the story emphasizes living in an isolated present. What’s right? The idea of subjective time (decades passing for others while you’re “frozen”) echoes relativity’s time dilation, though on a biological rather than gravitational scale. What’s wrong? The film sidesteps true time travel, so it doesn’t engage with paradoxes or causality. The tech feels plausible, but the lack of temporal consequences makes it less daring in exploring time’s mechanics.",
  "Tenet":"Nolan’s Tenet is a brain-twisting thriller where the Protagonist (John David Washington) battles a future threat using “inversion,” a process where objects and people move backward in time. The film posits a single timeline where the past and future coexist—events are fixed, and changing the past is impossible because it’s already happened. Think bullets “un-firing” into guns. What’s right? The deterministic view aligns with block universe theory, where all moments in time are equally real and unchangeable. Entropy reversal is a clever sci-fi twist. What’s wrong? Inversion’s logistics (like breathing backward) defy thermodynamics and biology. The grandfather paradox is dodged by narrative fiat, not logic. Tenet’s visual spectacle outshines its occasionally incoherent rules",
  "Arrival":"Denis Villeneuve’s Arrival is a profound sci-fi drama where linguist Louise Banks (Amy Adams) deciphers an alien language after mysterious heptapods land on Earth. Time travel manifests as non-linear perception—learning the aliens’ language lets Louise “see” her future, influencing her present choices. The film suggests time is a fixed loop: the future informs the past, but nothing changes. What’s right? The Sapir-Whorf-inspired idea that language shapes perception is grounded in linguistics, and the non-linear time model echoes eternalist views in physics. What’s wrong? The mechanism for “seeing” the future is mystical, not scientific—language alone wouldn’t grant precognition. Arrival nails emotional resonance but leans on poetic license over testable theory.",
  "Doctor Strange":"Directed by Scott Derrickson, Doctor Strange follows neurosurgeon Stephen Strange (Benedict Cumberbatch) who becomes a sorcerer wielding the Time Stone. Time travel appears when Strange manipulates time to trap a cosmic entity, looping events until victory. The film’s rules are loose—changing the past creates localized loops or resets, not timeline splits. What’s right? The looping mechanism resembles a controlled “Groundhog Day” scenario, plausible in a magical framework where time is malleable. What’s wrong? The Time Stone’s powers are pure fantasy, ignoring physics (e.g., conservation of energy). The film doesn’t address paradoxes, hand-waving consequences for narrative convenience. It’s a dazzling visual feast, but time travel is more spell than science.",
  "Deadpool & Wolverine":"Directed by Shawn Levy, Deadpool & Wolverine is a raunchy, action-packed buddy comedy where Deadpool (Ryan Reynolds) and Wolverine (Hugh Jackman) navigate multiversal chaos. Time travel occurs via a device that jumps between timelines, not within one. Changing the past creates new timelines, not altering the original—a multiverse model akin to Endgame. What’s right? The multiverse approach sidesteps paradoxes, consistent with quantum branching theories. What’s wrong? The time-travel device is a plot McGuffin with zero scientific basis, and timeline rules feel inconsistent (e.g., how anchors work). The film prioritizes irreverent humor and heart over coherent temporal mechanics, making it a wild ride with shaky physics.",
  "Predestination":"Predestination (2014) is a mind-bending time travel movie that explores paradoxes and the concept of fate. It’s based on Robert A. Heinlein’s short story All You Zombies and follows a temporal agent (played by Ethan Hawke) who is tasked with stopping a criminal known as the Fizzle Bomber. - Predestination Paradox – This means that any attempt to change the past actually ensures that events unfold exactly as they were meant to. The protagonist unknowingly plays a role in creating the very events he is trying to prevent. - Bootstrap Paradox – This occurs when an object or person exists in a closed loop with no clear origin. In Predestination, the main character is both their own mother and father, creating a self-sustaining cycle of existence. What is right:The film does an excellent job of portraying the complexities of time travel without relying on typical sci-fi tropes. It presents a logically consistent (though unsettling) paradox that challenges the viewer’s perception of identity and fate. what is wrong:- While the movie is philosophically intriguing, it doesn’t offer a way out of the paradox—it suggests that free will is an illusion and that characters are trapped in an endless loop. Some viewers might find this deterministic approach frustrating.",
  "Loki":"Directed by Kate Herron (Season 1), Loki is a Marvel Disney+ series where the trickster god Loki (Tom Hiddleston) navigates the Time Variance Authority (TVA), a bureaucracy controlling multiversal timelines. The quantum realm isn’t explicit, but quantum mechanics underpins the multiverse, with branching timelines tied to quantum probabilities and a mysterious “Quantum Loom” managing reality. What’s right? The multiverse concept aligns with the many-worlds interpretation of quantum mechanics, where every quantum event spawns parallel realities. The idea of quantum entanglement influencing timelines is a creative nod to non-locality. What’s wrong? The Quantum Loom and TVA’s tech are narrative McGuffins, not grounded in quantum theory, and the multiverse’s rules are inconsistent. Loki uses quantum ideas as a mythic framework, prioritizing character drama over physics.",
  "Lucy":"Directed by Luc Besson, Lucy is a sci-fi action thriller where Lucy (Scarlett Johansson) gains superhuman abilities after a drug unlocks her brain’s potential. Quantum mechanics is invoked loosely as Lucy manipulates matter, perceives quantum states, and transcends space-time, becoming a godlike entity. The film suggests quantum physics governs consciousness and reality at its core. What’s right? The idea that quantum processes might influence consciousness echoes speculative theories like quantum mind hypotheses (e.g., Penrose-Hameroff). What’s wrong? The “10% brain myth” is debunked nonsense, and Lucy’s powers—reshaping reality, accessing all quantum states—are pure fantasy, far removed from actual quantum mechanics’ probabilistic nature. Lucy is a stylish fever dream, using quantum buzzwords for spectacle, not science.",
  "The Butterfly Effect":"Directed by Eric Bress and J. Mackye Gruber, The Butterfly Effect is a psychological thriller where Evan (Ashton Kutcher) alters his past, creating cascading changes in his present. Quantum mechanics isn’t explicit but is implied through the “butterfly effect,” a chaos theory concept linked to quantum systems’ sensitivity to initial conditions. The film posits that small quantum-like changes can reshape reality. What’s right? The butterfly effect is real in complex systems, and quantum mechanics amplifies this via uncertainty at subatomic scales, where tiny changes can have outsized impacts. What’s wrong? The film’s deterministic timeline shifts (changing the past rewrites the future) oversimplify quantum indeterminacy, and the mechanism for Evan’s “jumps” is psychological, not quantum. The Butterfly Effect uses quantum-adjacent ideas for emotional gut-punches, not scientific rigor.",
  "Everything Everywhere All at Once":"Directed by Daniel Kwan and Daniel Scheinert, Everything Everywhere All at Once is a genre-defying masterpiece where Evelyn Wang (Michelle Yeoh) navigates infinite multiverses to save reality. Quantum mechanics drives the plot: every choice spawns a new universe, and Evelyn “verse-jumps” by tapping into quantum probabilities. The multiverse is a chaotic tapestry of quantum possibilities. What’s right? The many-worlds interpretation of quantum mechanics, where every quantum event creates a parallel universe, is vividly realized, and the film’s chaotic probability-driven jumps reflect quantum superposition. What’s wrong? Verse-jumping via random actions (e.g., eating chapstick) is whimsical nonsense, and the multiverse’s accessibility defies quantum isolation of parallel states. Everything Everywhere uses quantum physics as a metaphor for choice and identity, blending absurdity with profound heart.",
  "Ant-Man and the Wasp: Quantumania":"Directed by Peyton Reed, Ant-Man and the Wasp: Quantumania dives into Marvel’s quantum realm, a subatomic dimension where Scott Lang (Paul Rudd), Hope van Dyne (Evangeline Lilly), and family confront the exiled Kang the Conqueror (Jonathan Majors). The quantum realm is a psychedelic micro-universe with bizarre physics, alien-like creatures, and time distortions. Quantum mechanics is central, with characters shrinking to subatomic scales and navigating a realm where classical physics breaks down. What’s right? The idea of a quantum realm loosely aligns with quantum mechanics’ subatomic scale, where particles behave unpredictably, and the film’s time anomalies nod to quantum superposition. What’s wrong? The quantum realm is pure sci-fi fantasy—its ecosystems, sentient beings, and tangible landscapes contradict the abstract, probabilistic nature of quantum systems. Quantumania uses quantum physics as a colorful plot device, prioritizing action over scientific depth.",
  "Apollo 13":"Directed by Ron Howard, Apollo 13 is a gripping docudrama recounting NASA’s ill-fated 1970 lunar mission. Astronauts Jim Lovell (Tom Hanks), Fred Haise (Bill Paxton), and Jack Swigert (Kevin Bacon) face disaster when an oxygen tank explodes en route to the moon, crippling their spacecraft. The film focuses on the moon as a tantalizing but unreachable goal, with Earth’s satellite looming large in the crew’s dreams and the mission’s stakes. What’s right? The film nails the physics of lunar travel—orbital mechanics, limited resources, and the slingshot trajectory around the moon are meticulously accurate, grounded in NASA’s records. What’s wrong? Some dramatic flourishes, like heightened interpersonal tension, are exaggerated for effect. Apollo 13 is a masterclass in realism, capturing humanity’s fragile reach for the moon with heart-pounding intensity.",
  "Xmen":"a fascinating take on time travel within the superhero genre. It blends two timelines—the dystopian future and the past—to explore how altering history can change the fate of mutants.- Alternate Timelines – Changing the past creates a new future, rather than a paradox.- Butterfly Effect – Small changes in history lead to massive consequences.- Grandfather Paradox Avoidance – The movie sidesteps paradoxes by focusing on consciousness transfer rather than physical time travel. What is right:- The film does a great job of showing how time travel can be used to rewrite history without contradicting itself. It also explores the emotional weight of changing the past, especially through Professor X and Magneto’s evolving relationship.what is wrong:- The mechanics of Kitty Pryde’s time travel ability are never fully explained—she suddenly has the power to send minds back in time, which wasn’t part of her abilities before. Also, some continuity issues arise when comparing this timeline to previous X-Men films.",
  "Looper":"Is a sci-fi thriller that explores time travel in a gritty, dystopian future. It follows Joe, a hitman known as a Looper, who kills targets sent back in time by criminal organizations. The twist? Eventually, every Looper must close their loop by killing their future self.The movie presents a fixed time loop where events in the past directly shape the future. Some key time travel elements include:- Closed Loop System – Future criminals send targets back in time to be eliminated, ensuring no trace of them exists.- Paradoxes & Cause-Effect – When Joe’s older self (Bruce Willis) escapes execution, it creates a ripple effect that alters the timeline.- Butterfly Effect – Small changes in the past drastically impact the future, especially regarding the mysterious Rainmaker.",
  "11.22.63":"is a time-travel thriller based on Stephen King's novel, exploring the idea of altering history—specifically, preventing the assassination of John F. Kennedy.How It Relates to Time TravelThe story follows Jake Epping, a teacher who discovers a portal that sends him back to 1960. He decides to stay in the past long enough to stop Lee Harvey Oswald from killing Kennedy in 1963. The show plays with:- The Rigidity of the Past – Time actively resists change, making it difficult for Jake to alter history.- Butterfly Effect – Small changes in the past lead to unintended consequences in the future.- Moral Dilemmas – Jake struggles with whether changing history is truly the right thing to do.What’s Right and Wrong in the Show- Right: The series does a great job of showing how time travel isn’t just about changing events—it’s about dealing with the consequences. It also captures the historical atmosphere of the early 1960s beautifully.- Wrong: The mechanics of time travel aren’t fully explained, and the idea that time actively fights back against change is more of a plot device than a scientific concept.Ultimately, the show raises deep questions about fate, free will, and the cost of rewriting history. Have you watched it yet, or are you just exploring time travel stories?",
  "Spiderman: no way home":"Directed by Jon Watts, Spider-Man: No Way Home swings into the Marvel multiverse, where Peter Parker (Tom Holland) grapples with his exposed identity as Spider-Man. Seeking help from Doctor Strange (Benedict Cumberbatch), Peter triggers a spell that fractures reality, pulling villains and alternate Spider-Men from other universes into his world. The multiverse is a chaotic collision of parallel realities, each with its own physics and history, populated by familiar faces like Green Goblin (Willem Dafoe) and Tobey Maguire’s Spider-Man. Multiversal mechanics are central, with the spell acting as a quantum-like catalyst that destabilizes reality’s boundaries. What’s right? The concept of a multiverse aligns with the many-worlds interpretation of quantum mechanics, where every choice or event spawns divergent universes, and the idea of cross-universe interactions echoes quantum entanglement’s non-local connections. What’s wrong? The multiverse’s accessibility via a magical spell is pure fantasy, not grounded in quantum theory, and the film’s rules—where only certain characters cross over—are arbitrary and inconsistent with probabilistic quantum systems. No Way Home uses the multiverse as a nostalgic spectacle, prioritizing emotional resonance and action over scientific depth."
  ,"Outlander":"Developed by Ronald D. Moore, Outlander is a sweeping historical fantasy drama following Claire Randall (Caitriona Balfe), a World War II nurse who, in 1945, touches mystical standing stones in Scotland and is transported to 1743. Thrust into the Jacobite era, Claire navigates danger, romance with Highlander Jamie Fraser (Sam Heughan), and the challenge of returning to her own time. Time travel is central, enabled by the stones, which act as portals to specific historical periods, with later seasons exploring further jumps and their consequences. The series posits a single-timeline model: changes in the past can alter the future, but the past resists major disruptions, creating tension as Claire and others try to influence history. What’s right? The idea that the past resists change echoes chaos theory’s inertia in complex systems, and the emotional toll of time travel aligns with speculative ideas about temporal disorientation affecting consciousness. The single-timeline approach avoids multiverse complexity, grounding the stakes in one reality. What’s wrong? The stones’ time travel mechanism is purely magical, with no basis in physics—quantum mechanics or relativity offer no precedent for such portals. The rules are inconsistent (e.g., why specific dates are targeted, how travelers survive temporal shifts unscathed), and the lack of paradoxes (like the grandfather paradox) is narratively convenient. Outlander uses time travel as a romantic and historical catalyst, prioritizing lush drama and character depth over scientific rigor."
  ,"Doctor Strange: into the multiverse of madness":"Directed by Sam Raimi, Doctor Strange in the Multiverse of Madness is a thrilling Marvel spectacle where Doctor Stephen Strange (Benedict Cumberbatch) navigates a fractured multiverse to protect America Chavez (Xochitl Gomez), a teen with universe-hopping powers, from a cosmic threat. The multiverse is a kaleidoscope of realities—think gothic mirror dimensions, apocalyptic wastelands, and utopian variants—each with distinct physical laws and versions of familiar heroes. Multiverse theory drives the chaos, with Strange’s spells and Chavez’s abilities tearing through reality’s fabric, unleashing cross-universal consequences. What’s right? The multiverse concept aligns with the many-worlds interpretation of quantum mechanics, where every quantum event spawns parallel universes, and the diversity of realities reflects theoretical variations in physical constants. The idea of “incursions” (colliding universes) echoes speculative cosmology. What’s wrong? The multiverse’s accessibility via magic or innate powers lacks scientific grounding—quantum mechanics doesn’t allow such tangible crossings. The film’s rules (e.g., dream-walking, selective universe access) are narratively convenient, not consistent with probabilistic quantum systems. Multiverse of Madness uses the multiverse as a visually dazzling playground, prioritizing horror-tinged action and emotional stakes over theoretical rigor."
  ,"Dune":"Directed by Denis Villeneuve, Dune is a sweeping sci-fi epic adapting Frank Herbert’s novel, set in a distant future where noble houses vie for control of the desert planet Arrakis, the only source of “spice,” a resource vital for interstellar travel. Young Paul Atreides (Timothée Chalamet) navigates political intrigue, betrayal, and his destiny among Arrakis’ Fremen people, with space as a vast galactic canvas linking planets like Caladan and Giedi Prime. Space is depicted through advanced spacecraft (guided by spice-enhanced navigators), harsh planetary ecosystems, and the absence of traditional aliens, though the sandworms of Arrakis serve as enigmatic, quasi-alien lifeforms. The film emphasizes humanity’s colonization of the cosmos and the ecological stakes of alien worlds. What’s right? The concept of planets with unique ecosystems (Arrakis’ desert, Caladan’s oceans) aligns with exoplanet diversity, and spice as a navigation aid echoes theoretical needs for precise interstellar travel calculations, possibly tied to relativity or quantum navigation. The sandworms’ biology feels plausible for extreme alien environments. What’s wrong? The mechanics of spice-fueled space travel are vague, lacking grounding in physics—faster-than-light travel or “folding space” ignores energy constraints or relativity’s limits. The absence of aliens in a galaxy-spanning empire feels narratively convenient, sidestepping astrobiology’s likelihood of extraterrestrial life. Dune uses space as a mythic backdrop, prioritizing political and spiritual drama over astrophysical precision."
  ,"Gravity":"Directed by Alfonso Cuarón, Gravity is a tense sci-fi thriller where astronaut Ryan Stone (Sandra Bullock) fights for survival after a debris storm destroys her space shuttle in Earth’s orbit. Space is a stark, silent void, with the Earth’s glowing curve, the sun’s harsh light, and orbiting stations as the only landmarks. No aliens or distant planets appear—just the brutal reality of low Earth orbit. What’s right? The film’s physics are exceptionally accurate: zero-gravity motion, the vacuum’s lethality, and orbital debris hazards reflect NASA’s real challenges. The sun’s role in powering equipment is realistic. What’s wrong? The proximity of space stations (e.g., ISS to Tiangong) is exaggerated for drama, and Stone’s repeated survival pushes human physiology beyond plausible limits. Gravity captures space’s awe and peril with visceral precision, prioritizing technical realism over narrative embellishment."
  ,"Ad Astra":"Directed by James Gray, Ad Astra is a contemplative sci-fi drama following astronaut Roy McBride (Brad Pitt) on a journey to Neptune to stop a cosmic threat tied to his father’s lost mission. Space spans the solar system, with pitstops on a commercialized moon, a bureaucratic Mars, and the desolate outer planets. No aliens appear, but space’s vastness amplifies human isolation. What’s right? The near-future depiction of lunar bases and Mars outposts feels plausible, grounded in current space exploration trends. Cosmic radiation and psychological strain are acknowledged as real hazards. What’s wrong? The trip to Neptune is unrealistically fast, defying propulsion limits, and the anti-matter surge plot is scientifically dubious, lacking clear quantum or relativistic grounding. Ad Astra uses space as a introspective void, favoring emotional depth over hard science."
  ,"Guardians of the Galaxy":"Directed by James Gunn, Guardians of the Galaxy is a rollicking sci-fi adventure where outlaws like Peter Quill (Chris Pratt) and Gamora (Zoe Saldana) race across alien planets and space stations to secure a cosmic artifact. Space is a vibrant galaxy teeming with aliens (Kree, Ravagers, even a sentient planet), exotic worlds, and neon-lit ships. What’s right? The diversity of alien species and planetary environments captures the speculative breadth of exobiology, and the galaxy’s scale feels appropriately immense. What’s wrong? The physics are fantastical—planets with breathable air, instant interstellar jumps, and living celestial bodies defy thermodynamics and astrophysics. Alien biology (e.g., Groot’s plant-human hybrid) lacks evolutionary plausibility. Guardians transforms space into a cosmic carnival, prioritizing humor and heart over scientific accuracy."
  ,"The Martian":"Directed by Ridley Scott, The Martian is a gripping survival tale about astronaut Mark Watney (Matt Damon), stranded on Mars after a mission mishap. The red planet is a dusty, sunlit wasteland, with no aliens but plenty of challenges—thin atmosphere, freezing nights, and barren soil. Space is both Earth’s distant neighbor and a lethal frontier. What’s right? Mars’ depiction—its low gravity, weak sunlight, and rocky terrain—matches NASA’s data. Watney’s scientific hacks, like growing potatoes, are rooted in plausible astrobiology and chemistry. What’s wrong? The opening storm’s intensity is exaggerated (Mars’ thin atmosphere can’t support such winds), and the rescue timeline compresses real interplanetary travel constraints. The Martian makes space a stage for human resilience, blending rigorous science with cinematic optimism."
  ,"Alien Covenant":"Directed by Ridley Scott, Alien: Covenant is a dark sci-fi horror where a colony ship’s crew discovers a seemingly idyllic planet, only to encounter deadly xenomorphs and a rogue android (Michael Fassbender). Space is a distant frontier, with the planet’s lush, Earth-like surface hiding alien terrors. The xenomorphs represent hostile extraterrestrial life. What’s right? The concept of a habitable exoplanet with unique lifeforms aligns with astrobiology’s search for Goldilocks zones. The xenomorphs’ aggressive evolution feels like a plausible extreme of alien adaptation. What’s wrong? The planet’s perfect habitability (breathable air, Earth-like gravity) is overly convenient, and the xenomorphs’ rapid development defies biological constraints. Space travel logistics (e.g., cryosleep) are glossed over. Covenant uses space as a nightmarish canvas, prioritizing horror over astrophysical detail."
  ,"First Man":"Directed by Damien Chazelle, First Man is an intimate biopic of Neil Armstrong (Ryan Gosling), chronicling the Apollo 11 mission to land on the moon. Space is a perilous frontier, with the moon’s gray, cratered surface lit by the sun’s unfiltered glare. No aliens or distant planets, just Earth’s satellite as a historic milestone. What’s right? The film’s portrayal of lunar travel—shaky capsules, precise orbital maneuvers, and the moon’s desolate beauty—is meticulously accurate, drawn from NASA’s records. The sun’s role in navigation and visibility is realistic. What’s wrong? Minor dramatic liberties (e.g., emotional emphasis on personal loss) slightly embellish the historical record, but the science is near-flawless. First Man renders space as a testament to human ambition, grounding cosmic triumph in gritty realism."
  ,"Sunshine":"Directed by Danny Boyle, Sunshine is a haunting sci-fi thriller where a crew, including Cillian Murphy’s physicist, embarks on a mission to detonate a stellar bomb and revive the dying sun. Space is the solar system’s core, with the sun’s blazing corona and lethal radiation dominating the narrative. No aliens or planets, just the star’s raw power. What’s right? The sun’s centrality as a finite energy source is accurate (it will eventually die, though not soon), and the film captures solar radiation’s dangers and gravitational pull. What’s wrong? The premise of the sun failing in decades is absurd—it has billions of years left. The “Q-ball” bomb is fictional, with no basis in stellar physics, and crew survival near the sun stretches plausibility. Sunshine uses space as a metaphysical arena, blending scientific nods with existential awe."

  ,"ET":"Directed by Steven Spielberg, E.T. the Extra-Terrestrial is a heartwarming sci-fi classic about Elliott (Henry Thomas), a young boy who befriends an alien stranded on Earth after his spaceship departs. E.T., a gentle, telepathic extraterrestrial, hides in Elliott’s suburban home while they work to signal his kind for rescue, evading government pursuit. Space is depicted through E.T.’s advanced technology—his ship’s swift interstellar travel and a glowing communication device—set against the vast, unseen cosmos from which he hails. The film emphasizes the wonder of alien life and Earth’s place in a populated universe. What’s right? The portrayal of an intelligent, biologically distinct alien aligns with astrobiology’s speculation about diverse extraterrestrial life. The concept of interstellar travel, while vague, nods to theoretical possibilities like wormholes or faster-than-light propulsion. What’s wrong? E.T.’s biology (e.g., glowing heart, psychic links) and the ship’s mechanics (instant takeoffs, no visible energy source) are pure fantasy, ignoring physics’ constraints like energy costs or relativity’s limits. The ease of Earth-alien contact overlooks cosmic distances and communication barriers. E.T. uses space as an emotional canvas, prioritizing tender connection over astrophysical accuracy."
};

document.querySelectorAll(".movie-gallery img").forEach(img => {
  img.addEventListener("click", () => {
    const titlez = img.alt;
    bigImage.src = img.src;
    bigTitle.textContent = titlez;
    bigDescription.textContent = descriptions[titlez];
    bigmovie.style.display = "flex";
  });
});

bigmovie.addEventListener("click", (tapped) => {
  if (tapped.target === bigmovie) {
    bigmovie.style.display = "none";
  }
});
const categories = document.querySelectorAll('.categories');
let gradient = "linear-gradient(90deg, #000000, rgb(92, 69, 15))";
let look = document.createElement('div');
look.style.position = 'fixed';
look.style.top = '0';
look.style.left = '0';
look.style.width = '100%';
look.style.height = '100%';
look.style.zIndex = '-1';
look.style.pointerEvents = 'none';
look.style.opacity = '0';
look.style.transition = 'opacity 1s ease';
document.body.appendChild(look);

function change(gradient2) {
  if (gradient2 === gradient) return;

  look.style.background = gradient2;
  look.style.opacity = '1';

  setTimeout(() => {
    document.body.style.background = gradient2;
    look.style.opacity = '0';
    gradient = gradient2;
  }, 1000);
}

window.addEventListener('scroll', () => {
  categories.forEach(section => {
    const mid = section.getBoundingClientRect();
    if (mid.top <= window.innerHeight / 2 && mid.bottom >= window.innerHeight / 2) {
      const id = section.id;
      let gradient2 = "";

      switch (id) {
        case "time-traveling":
          gradient2 = "linear-gradient(90deg, #000000,rgb(92, 69, 15) )";
          break;
        case "space":
          gradient2 = "linear-gradient(90deg, #000000,rgb(13, 50, 83))";
          break;
        case "QuantumVerses":
          gradient2 = "linear-gradient(90deg, #000000,rgb(60, 57, 77))";
          break;
          case "vidz4js":
          gradient2 = "linear-gradient(90deg, #000000,rgb(77, 57, 57))";
          break;
      }

      change(gradient2);
    }
  });
});